[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "erc4337/=lib/erc4337/contracts/",
    "forge-std/=lib/forge-std/src/",
    "@prb/math/=lib/prb-math/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "tokenbound/=lib/tokenbound/src/",
    "erc6551/=lib/erc6551/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
]
