[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@rari-capital/solmate/=lib/optimism/packages/contracts-bedrock/lib/solmate/",
    "erc4337/=lib/erc4337/contracts/",
    "erc6551/=lib/erc6551/src/",
    "openzeppelin-contracts/=lib/erc6551/lib/openzeppelin-contracts/contracts/",
    "optimism-contracts/=lib/optimism/packages/contracts-bedrock/src/",
]
